# Configuration file for markdownlint
# https://github.com/DavidAnson/markdownlint-cli2#markdownlint-cli2jsonc
# https://github.com/DavidAnson/markdownlint-cli2/blob/main/test/markdownlint-cli2-yaml-example/.markdownlint-cli2.yaml

fix: true
ignores: []
config:
  # Rules Documentation:https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
  default: true

  # line-length
  MD013: false
